Error: 
  at get (tests/js_error/source_locations/statement/return/await_throws_module.js:2:63)
  at generator (tests/js_error/source_locations/statement/return/await_throws_module.js:5:3)
  at next (<native>)
  at <module> (tests/js_error/source_locations/statement/return/await_throws_module.js:9:7)
  at <anonymous> (<native>)
  at <anonymous> (<native>)
